### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by forkiesassds**

### CODE REVIEW

**Comment by chaziz94** [comment]
why is it telling us about non-existing dependencies.

this is using composer, not node.

**Comment by forkiesassds** [comment]
> 
> 
> why is it telling us about non-existing dependencies.
> 
> this is using composer, not node.

bootstrap, that's why.

**Comment by chaziz94** [comment]
ok so there's a vuln with a bootstrap dependecy right

**Comment by forkiesassds** [comment]
> 
> 
> ok so there's a vuln with a bootstrap dependecy right

yes

**Pull request closed without merging**
